apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: fluentd
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16.5-debian-elasticsearch7-amd64-1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /fluentd/etc
              name: configpath
              readOnly: true  # Fixed the incorrect field name
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: dockercontainers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: configpath
          configMap:
            name: fluentd-config  # Changed from hostPath to ConfigMap
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

