apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-cluster-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/es-cluster-2

