apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-1  # New name to avoid conflicts
spec:
  capacity:
    storage: 10Gi  # Adjust as necessary
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Empty string for static provisioning, or use a default StorageClass name if available
  hostPath:
    path: /data/elasticsearch  # Adjust according to your environment (or use another provisioner)
