apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-es-cluster-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-elasticsearch-1  # Manually bind to the available PV

